# Generated by Django 4.2.3 on 2023-07-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_remove_quizanalytics_total_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
