# Generated by Django 4.2.2 on 2023-07-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_quizattempt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanalytics',
            name='total_questions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
