# Generated by Django 4.2.2 on 2023-08-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_quizanalytics_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
